# Tarefa 01

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os monitores
- Divirta-se :)

In [74]:
# Importando bibliotecas para manipulação de dados
import pandas as pd

# Importando biblioteca para download de dados financeiros
import yfinance as yf

# Importando bibliotecas para visualização de dados
import plotly.express as px
from plotly import graph_objects as go

# Importando biblioteca para manipulação de arquivos e diretórios
import os

#### 1. Baixando dados de ativos
    1. Baixe os dados de três ativos da sua escolha do Yahoo Finance, correspondente a um período de pelo menos 2 anos até a data mais recente.
    2. Salve esses dados para que você possa utilizá-los na próxima tarefa.

In [75]:
# Definindo a lista de ativos que serão analisados
ativos = ['INTC', 'AMD', 'IBM']

# Definindo a data inicial para o período de análise
data_inicial = '2023-04-15'

# Baixando os dados históricos dos ativos selecionados a partir da data inicial usando a biblioteca yfinance
df_ativos = yf.download(ativos, start=data_inicial)

# Removendo os nomes dos níveis de coluna do DataFrame para simplificar a manipulação dos dados
df_ativos.columns.names = [None, None]

# Exibindo o DataFrame com os dados baixados
df_ativos

[*********************100%***********************]  3 of 3 completed

                Close                              High              \
                  AMD         IBM       INTC        AMD         IBM
Date
2023-04-17  89.870003  118.179916  31.369518  90.690002  119.012041
2023-04-18  89.779999  118.142929  31.066952  92.160004  118.975046
2023-04-19  89.940002  116.793053  30.403254  90.540001  117.403279
2023-04-20  90.110001  116.830048  30.120209  91.580002  121.101607
2023-04-21  88.430000  116.247551  29.573627  89.800003  117.144388
...               ...         ...        ...        ...         ...
2025-04-11  93.400002  235.479996  19.740000  94.760002  237.580002
2025-04-14  94.500000  239.059998  20.309999  97.370003  241.770004
2025-04-15  95.290001  240.699997  19.850000  96.849998  241.529999
2025-04-16  88.290001  238.570007  19.230000  90.470001  243.300003
2025-04-17  87.500000  238.809998  18.930000  89.029999  241.779999

                             Low                              Open  \
                 INTC        AMD         IBM       INTC        AMD
Date
2023-04-17  31.857532  88.300003  117.236847  31.008389  90.230003
2023-04-18  31.681848  89.330002  117.745359  31.018151  91.610001
2023-04-19  30.764385  88.220001  115.849983  30.334932  88.510002
2023-04-20  30.500859  88.730003  116.349262  29.973803  88.830002
2023-04-21  30.100683  88.059998  115.822238  29.505306  89.800003
...               ...        ...         ...        ...        ...
2025-04-11  19.799999  90.500000  227.509995  18.180000  90.510002
2025-04-14  21.049999  93.449997  236.729996  19.980000  97.110001
2025-04-15  20.469999  94.620003  238.270004  19.809999  94.660004
2025-04-16  19.430000  85.300003  235.889999  18.719999  87.610001
2025-04-17  19.100000  86.519997  237.399994  18.559999  88.839996

                                     Volume
                   IBM       INTC       AMD      IBM       INTC
Date
2023-04-17  118.623718  31.184074  47250800  3662700   29601100
2023-04-18  118.475779  31.652569  46246300  3193800   26041400
2023-04-19  116.959478  30.354453  37344500  7014400   25746600
2023-04-20  120.334203  30.022606  47082700  9749600   30255100
2023-04-21  116.497185  30.100683  41118300  6725400   28655800
...                ...        ...       ...      ...        ...
2025-04-11  229.720001  19.250000  57892600  4325900  128425800
2025-04-14  239.770004  20.590000  36003000  3321500  101964400
2025-04-15  239.550003  20.200001  28116500  3363700   64056900
2025-04-16  240.279999  19.340000  62109000  4869900   89469700
2025-04-17  239.679993  18.910000  34693400  4626900   85433400

[504 rows x 15 columns]

#### 2. Observando a volatilidade dentro do dia
1. Calcule a amplitude de variação do valor do ativo dentro do dia. Essa amplitude você pode calcular com um comando simples de adicionar uma coluna no Pandas: (valor máximo - valor mínimo).
2. Monte um gráfico de linha mostrando a variação dessa amplitude ao longo do período coletado, por ativo.
3. Veja se consegue identificar que ativo apresentou maior volatilidade.

In [76]:
# Selecionando as colunas 'High' e 'Low' do DataFrame df_ativos
# Empilhando os dados para transformar o DataFrame em um formato longo (long format)
# Resetando o índice para que as colunas do índice original se tornem colunas regulares
temp_df = df_ativos[['High', 'Low']].stack().reset_index()

C:\Users\hfasa\AppData\Local\Temp\ipykernel_22456\619224188.py:4: FutureWarning:

The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.

In [77]:
# Calculando a volatilidade diária para cada ativo
temp_df['Volatilidade'] = temp_df['High'] - temp_df['Low']  # Subtraindo o valor mínimo (Low) do valor máximo (High) para obter a amplitude diária
temp_df['Volatilidade'] = temp_df['Volatilidade'].abs()  # Garantindo que a volatilidade seja sempre positiva
temp_df['Volatilidade'] = temp_df['Volatilidade'].round(2)  # Arredondando os valores da volatilidade para duas casas decimais

# Renomeando a coluna 'level_1' para 'Ticker' para melhor identificação dos ativos
temp_df.rename(columns={'level_1': 'Ticker'}, inplace=True)

# Exibindo o DataFrame atualizado
temp_df

           Date Ticker        High         Low  Volatilidade
0    2023-04-17    AMD   90.690002   88.300003          2.39
1    2023-04-17    IBM  119.012041  117.236847          1.78
2    2023-04-17   INTC   31.857532   31.008389          0.85
3    2023-04-18    AMD   92.160004   89.330002          2.83
4    2023-04-18    IBM  118.975046  117.745359          1.23
...         ...    ...         ...         ...           ...
1507 2025-04-16    IBM  243.300003  235.889999          7.41
1508 2025-04-16   INTC   19.430000   18.719999          0.71
1509 2025-04-17    AMD   89.029999   86.519997          2.51
1510 2025-04-17    IBM  241.779999  237.399994          4.38
1511 2025-04-17   INTC   19.100000   18.559999          0.54

[1512 rows x 5 columns]

In [78]:
# Extraindo apenas os valores High e Low
# Seleciona as colunas 'High' e 'Low' do DataFrame 'df_ativos' para os cálculos de volatilidade
high = df_ativos['High']
low = df_ativos['Low']

# Calculando a volatilidade
# Subtrai os valores mínimos (Low) dos valores máximos (High) para calcular a amplitude diária
# Aplica o valor absoluto para garantir que a volatilidade seja positiva e arredonda para duas casas decimais
volatilidade = (high - low).abs()

# Remove o nome do nível de coluna, caso exista, para simplificar a estrutura do DataFrame
volatilidade.columns.name = None

In [79]:
# Exibindo o DataFrame 'volatilidade'
# Este DataFrame contém a volatilidade diária calculada para cada ativo (AMD, IBM, INTC),
volatilidade

                 AMD        IBM      INTC
Date
2023-04-17  2.389999   1.775193  0.849143
2023-04-18  2.830002   1.229687  0.663697
2023-04-19  2.320000   1.553296  0.429453
2023-04-20  2.849998   4.752345  0.527056
2023-04-21  1.740005   1.322151  0.595377
...              ...        ...       ...
2025-04-11  4.260002  10.070007  1.619999
2025-04-14  3.920006   5.040009  1.070000
2025-04-15  2.229996   3.259995  0.660000
2025-04-16  5.169998   7.410004  0.710001
2025-04-17  2.510002   4.380005  0.540001

[504 rows x 3 columns]

In [80]:
# Recriando as colunas multi-index corretas para a volatilidade
# Aqui, as colunas do DataFrame 'volatilidade' são convertidas para um formato de MultiIndex,
# onde o nível superior é 'Volatilidade' e o nível inferior contém os nomes das colunas originais (AMD, IBM, INTC).
volatilidade.columns = pd.MultiIndex.from_product([['Volatilidade'], volatilidade.columns])

# Concatenando o DataFrame 'volatilidade' com o DataFrame 'df_ativos'
# Isso adiciona as colunas de volatilidade ao DataFrame principal 'df_ativos', alinhando os índices.
df_ativos = pd.concat([df_ativos, volatilidade], axis=1)

# Ordenando as colunas do DataFrame 'df_ativos', se necessário
# Isso organiza as colunas em ordem alfabética ou lógica, dependendo da estrutura do MultiIndex.
df_ativos = df_ativos.sort_index(axis=1)

In [81]:
df_ativos.round(2)

            Close                  High                   Low                 \
              AMD     IBM   INTC    AMD     IBM   INTC    AMD     IBM   INTC
Date
2023-04-17  89.87  118.18  31.37  90.69  119.01  31.86  88.30  117.24  31.01
2023-04-18  89.78  118.14  31.07  92.16  118.98  31.68  89.33  117.75  31.02
2023-04-19  89.94  116.79  30.40  90.54  117.40  30.76  88.22  115.85  30.33
2023-04-20  90.11  116.83  30.12  91.58  121.10  30.50  88.73  116.35  29.97
2023-04-21  88.43  116.25  29.57  89.80  117.14  30.10  88.06  115.82  29.51
...           ...     ...    ...    ...     ...    ...    ...     ...    ...
2025-04-11  93.40  235.48  19.74  94.76  237.58  19.80  90.50  227.51  18.18
2025-04-14  94.50  239.06  20.31  97.37  241.77  21.05  93.45  236.73  19.98
2025-04-15  95.29  240.70  19.85  96.85  241.53  20.47  94.62  238.27  19.81
2025-04-16  88.29  238.57  19.23  90.47  243.30  19.43  85.30  235.89  18.72
2025-04-17  87.50  238.81  18.93  89.03  241.78  19.10  86.52  237.40  18.56

             Open                Volatilidade                 Volume           \
              AMD     IBM   INTC          AMD    IBM  INTC       AMD      IBM
Date
2023-04-17  90.23  118.62  31.18         2.39   1.78  0.85  47250800  3662700
2023-04-18  91.61  118.48  31.65         2.83   1.23  0.66  46246300  3193800
2023-04-19  88.51  116.96  30.35         2.32   1.55  0.43  37344500  7014400
2023-04-20  88.83  120.33  30.02         2.85   4.75  0.53  47082700  9749600
2023-04-21  89.80  116.50  30.10         1.74   1.32  0.60  41118300  6725400
...           ...     ...    ...          ...    ...   ...       ...      ...
2025-04-11  90.51  229.72  19.25         4.26  10.07  1.62  57892600  4325900
2025-04-14  97.11  239.77  20.59         3.92   5.04  1.07  36003000  3321500
2025-04-15  94.66  239.55  20.20         2.23   3.26  0.66  28116500  3363700
2025-04-16  87.61  240.28  19.34         5.17   7.41  0.71  62109000  4869900
2025-04-17  88.84  239.68  18.91         2.51   4.38  0.54  34693400  4626900


                 INTC
Date
2023-04-17   29601100
2023-04-18   26041400
2023-04-19   25746600
2023-04-20   30255100
2023-04-21   28655800
...               ...
2025-04-11  128425800
2025-04-14  101964400
2025-04-15   64056900
2025-04-16   89469700
2025-04-17   85433400

[504 rows x 18 columns]

In [82]:
df_ativos.columns

MultiIndex([(       'Close',  'AMD'),
            (       'Close',  'IBM'),
            (       'Close', 'INTC'),
            (        'High',  'AMD'),
            (        'High',  'IBM'),
            (        'High', 'INTC'),
            (         'Low',  'AMD'),
            (         'Low',  'IBM'),
            (         'Low', 'INTC'),
            (        'Open',  'AMD'),
            (        'Open',  'IBM'),
            (        'Open', 'INTC'),
            ('Volatilidade',  'AMD'),
            ('Volatilidade',  'IBM'),
            ('Volatilidade', 'INTC'),
            (      'Volume',  'AMD'),
            (      'Volume',  'IBM'),
            (      'Volume', 'INTC')],
           )

In [83]:
fig = px.line(temp_df, x='Date', y='Volatilidade', color='Ticker', 
			  title='Volatilidade Diária', 
			  labels={'Date': 'Data', 'Volatilidade': 'Volatilidade'}, 
			  markers=True, 
			  template='plotly_white')
fig.update_traces(mode='lines+markers')
fig.show()

In [85]:
os.makedirs('./output', exist_ok=True)
# Salvando o DataFrame 'df_ativos' em um arquivo CSV
df_ativos.to_csv('./output/Registro da bolsa - Gigantes dos semicondutores.csv')

Conclusão: Embora o papel da AMD se mantenha consistentemente acima dos outros dois, ele também é o mais volátil, apresentando com maior frequência picos acentuados e quedas bruscas. Ainda assim, seu valor permanece superior ao dos demais.