# Tarefa 02

- Leia os enunciados com atenção
- Saiba que pode haver mais de uma resposta correta
- Insira novas células de código sempre que achar necessário
- Em caso de dúvidas, procure os monitores
- Divirta-se :)

#### 1. Carregue os dados da tarefa anterior

In [218]:
# Importando bibliotecas para manipulação de dados
import pandas as pd

# Importando biblioteca para download de dados financeiros
import yfinance as yf

# Importando bibliotecas para visualização de dados
import plotly.express as px
from plotly import graph_objects as go
from plotly.graph_objs import Layout

# Importando biblioteca para manipulação de arquivos e diretórios
import os

In [219]:
df = pd.read_csv(
    r"C:\Users\hfasa\Desktop\Wares\DEV\Estudos\Cientista_de_dados\7. Gestão avançada de Dados e Desenvolvimento de aplicações\2. Descritiva III - Gráficos interativos\Prática\Pratique 1\output\Registro da bolsa - Gigantes dos semicondutores.csv",
    header=[0, 1],
    index_col=0,
)
df.round(2)

            Close                  High                   Low                 \
              AMD     IBM   INTC    AMD     IBM   INTC    AMD     IBM   INTC
Date
2023-04-17  89.87  118.18  31.37  90.69  119.01  31.86  88.30  117.24  31.01
2023-04-18  89.78  118.14  31.07  92.16  118.98  31.68  89.33  117.75  31.02
2023-04-19  89.94  116.79  30.40  90.54  117.40  30.76  88.22  115.85  30.33
2023-04-20  90.11  116.83  30.12  91.58  121.10  30.50  88.73  116.35  29.97
2023-04-21  88.43  116.25  29.57  89.80  117.14  30.10  88.06  115.82  29.51
...           ...     ...    ...    ...     ...    ...    ...     ...    ...
2025-04-14  94.50  239.06  20.31  97.37  241.77  21.05  93.45  236.73  19.98
2025-04-15  95.29  240.70  19.85  96.85  241.53  20.47  94.62  238.27  19.81
2025-04-16  88.29  238.57  19.23  90.47  243.30  19.43  85.30  235.89  18.72
2025-04-17  87.50  238.81  18.93  89.03  241.78  19.10  86.52  237.40  18.56
2025-04-21  85.56  236.22  18.84  86.14  240.81  18.99  83.75  232.93  18.25

             Open                Volatilidade                Volume           \
              AMD     IBM   INTC          AMD   IBM  INTC       AMD      IBM
Date
2023-04-17  90.23  118.62  31.18         2.39  1.78  0.85  47250800  3662700
2023-04-18  91.61  118.48  31.65         2.83  1.23  0.66  46246300  3193800
2023-04-19  88.51  116.96  30.35         2.32  1.55  0.43  37344500  7014400
2023-04-20  88.83  120.33  30.02         2.85  4.75  0.53  47082700  9749600
2023-04-21  89.80  116.50  30.10         1.74  1.32  0.60  41118300  6725400
...           ...     ...    ...          ...   ...   ...       ...      ...
2025-04-14  97.11  239.77  20.59         3.92  5.04  1.07  36003000  3321500
2025-04-15  94.66  239.55  20.20         2.23  3.26  0.66  28116500  3363700
2025-04-16  87.61  240.28  19.34         5.17  7.41  0.71  62109000  4869900
2025-04-17  88.84  239.68  18.91         2.51  4.38  0.54  34693400  4626900
2025-04-21  86.02  238.07  18.93         2.39  7.88  0.74  33774700  4907500


                 INTC
Date
2023-04-17   29601100
2023-04-18   26041400
2023-04-19   25746600
2023-04-20   30255100
2023-04-21   28655800
...               ...
2025-04-14  101964400
2025-04-15   64056900
2025-04-16   89469700
2025-04-17   85433400
2025-04-21   72239200

[505 rows x 18 columns]

#### 2. Média móvel

1. Faça uma média móvel  em 90 dias dos valores de fechamento ajustados dos ativos que você escolheu
2. Utilizando a fução ```rolling()```, calcule o desvio padrão desses ativos ao longo do tempo, utilizando a mesma janela móvel do item acima
2. Monte um gráfico de linhas para as médias móveis dos ativos da sua base
4. Monte um gráfico de linhas para os desvios padrão em janela móvel
5. Compare os dois gráficos que você fez com o da tarefa anterior. Veja se eles apontam conclusões semelhantes quanto aos períodos de maior volatilidade (variação) dos ativos.

In [220]:
df

                Close                              High              \
                  AMD         IBM       INTC        AMD         IBM
Date
2023-04-17  89.870003  118.179916  31.369522  90.690002  119.012041
2023-04-18  89.779999  118.142937  31.066956  92.160004  118.975054
2023-04-19  89.940002  116.793045  30.403254  90.540001  117.403272
2023-04-20  90.110001  116.830032  30.120205  91.580002  121.101591
2023-04-21  88.430000  116.247551  29.573629  89.800003  117.144388
...               ...         ...        ...        ...         ...
2025-04-14  94.500000  239.059998  20.309999  97.370003  241.770004
2025-04-15  95.290001  240.699997  19.850000  96.849998  241.529999
2025-04-16  88.290001  238.570007  19.230000  90.470001  243.300003
2025-04-17  87.500000  238.809998  18.930000  89.029999  241.779999
2025-04-21  85.559998  236.220001  18.840000  86.139999  240.809998

                             Low                              Open  \
                 INTC        AMD         IBM       INTC        AMD
Date
2023-04-17  31.857536  88.300003  117.236847  31.008393  90.230003
2023-04-18  31.681852  89.330002  117.745367  31.018155  91.610001
2023-04-19  30.764385  88.220001  115.849976  30.334932  88.510002
2023-04-20  30.500855  88.730003  116.349246  29.973799  88.830002
2023-04-21  30.100685  88.059998  115.822238  29.505308  89.800003
...               ...        ...         ...        ...        ...
2025-04-14  21.049999  93.449997  236.729996  19.980000  97.110001
2025-04-15  20.469999  94.620003  238.270004  19.809999  94.660004
2025-04-16  19.430000  85.300003  235.889999  18.719999  87.610001
2025-04-17  19.100000  86.519997  237.399994  18.559999  88.839996
2025-04-21  18.990000  83.750000  232.929993  18.250000  86.019997

                                  Volatilidade                        Volume  \
                   IBM       INTC          AMD       IBM      INTC       AMD
Date
2023-04-17  118.623718  31.184078     2.389999  1.775193  0.849143  47250800
2023-04-18  118.475786  31.652572     2.830002  1.229687  0.663697  46246300
2023-04-19  116.959470  30.354453     2.320000  1.553296  0.429453  37344500
2023-04-20  120.334187  30.022602     2.849998  4.752345  0.527056  47082700
2023-04-21  116.497185  30.100685     1.740005  1.322151  0.595377  41118300
...                ...        ...          ...       ...       ...       ...
2025-04-14  239.770004  20.590000     3.920006  5.040009  1.070000  36003000
2025-04-15  239.550003  20.200001     2.229996  3.259995  0.660000  28116500
2025-04-16  240.279999  19.340000     5.169998  7.410004  0.710001  62109000
2025-04-17  239.679993  18.910000     2.510002  4.380005  0.540001  34693400
2025-04-21  238.070007  18.930000     2.389999  7.880005  0.740000  33774700


                IBM       INTC
Date
2023-04-17  3662700   29601100
2023-04-18  3193800   26041400
2023-04-19  7014400   25746600
2023-04-20  9749600   30255100
2023-04-21  6725400   28655800
...             ...        ...
2025-04-14  3321500  101964400
2025-04-15  3363700   64056900
2025-04-16  4869900   89469700
2025-04-17  4626900   85433400
2025-04-21  4907500   72239200

[505 rows x 18 columns]

In [221]:
df_mv_90 = df.Close.rolling(window=90).mean()
df_mv_90 = df_mv_90.stack().reset_index()
df_mv_90.columns = ["Data", 'Ativo',"Média Móvel 90 dias"]
df_mv_90

            Data Ativo  Média Móvel 90 dias
0     2023-08-23   AMD           108.404556
1     2023-08-23   IBM           124.796768
2     2023-08-23  INTC            31.737636
3     2023-08-24   AMD           108.537111
4     2023-08-24   IBM           124.995675
...          ...   ...                  ...
1243  2025-04-17   IBM           239.341399
1244  2025-04-17  INTC            21.332333
1245  2025-04-21   AMD           110.563000
1246  2025-04-21   IBM           239.338681
1247  2025-04-21  INTC            21.309222

[1248 rows x 3 columns]

In [222]:
fig = px.line(df_mv_90, x='Data', y='Média Móvel 90 dias', color='Ativo', 
			  title='Média Móvel de 90 dias',
              labels={'Data': 'Data', 'Média Móvel 90 dias': 'Média Móvel 90 dias'}, 
			  markers=True, 
			  template='plotly_white')
fig.update_traces(mode='lines+markers')
fig.show()

In [223]:
df_std_90 = df.Close.rolling(window=90).std()
df_std_90 = df_std_90.stack().reset_index()
df_std_90.columns = ["Data", 'Ativo',"Desvio Padrão 90 dias"]
df_std_90

            Data Ativo  Desvio Padrão 90 dias
0     2023-08-23   AMD              11.555377
1     2023-08-23   IBM               7.174192
2     2023-08-23  INTC               2.188812
3     2023-08-24   AMD              11.407857
4     2023-08-24   IBM               7.236569
...          ...   ...                    ...
1243  2025-04-17   IBM              15.336534
1244  2025-04-17  INTC               2.032839
1245  2025-04-21   AMD              12.462583
1246  2025-04-21   IBM              15.337072
1247  2025-04-21  INTC               2.049337

[1248 rows x 3 columns]

In [224]:
fig = px.line(df_std_90, x='Data', y='Desvio Padrão 90 dias', color='Ativo', 
			  title='Desvio Padrão 90 dias',
              labels={'Data': 'Data', 'Desvio Padrão 90 dias': 'Desvio Padrão 90 dias'}, 
			  markers=True, 
			  template='plotly_white')
fig.update_traces(mode='lines+markers')
fig.show()

Resposta: O investimento mais consistente e de menor risco, neste caso, seria a Intel (INTC), que apresenta baixa volatilidade e comportamento estável ao longo do tempo. A AMD, por outro lado, demonstra alta volatilidade e uma tendência de queda nos últimos meses, o que indica maior risco. Já a IBM exibe uma trajetória de crescimento gradual e consistente, com níveis de volatilidade relativamente baixos na maior parte do período, mas com picos recentes. Esses aumentos de volatilidade sugerem que o mercado está direcionando maior atenção à ação, possivelmente em resposta a eventos ou expectativas relevantes.

#### 3. Gráfico de *candlestick*
1. Selecione o período dos últimos 60 dias (corridos) para um dos ativos da sua base
2. Monte um gráfico de *candlestick* para esses dados.

In [225]:
df.columns

MultiIndex([(       'Close',  'AMD'),
            (       'Close',  'IBM'),
            (       'Close', 'INTC'),
            (        'High',  'AMD'),
            (        'High',  'IBM'),
            (        'High', 'INTC'),
            (         'Low',  'AMD'),
            (         'Low',  'IBM'),
            (         'Low', 'INTC'),
            (        'Open',  'AMD'),
            (        'Open',  'IBM'),
            (        'Open', 'INTC'),
            ('Volatilidade',  'AMD'),
            ('Volatilidade',  'IBM'),
            ('Volatilidade', 'INTC'),
            (      'Volume',  'AMD'),
            (      'Volume',  'IBM'),
            (      'Volume', 'INTC')],
           )

In [226]:
lista_de_indicadores = ['Close', 'High','Low','Open', 'Volatilidade', 'Volume']
ativo = ['IBM'] * len(lista_de_indicadores)
colunas = list(zip(lista_de_indicadores, ativo))

In [227]:
df.tail(60)

                 Close                               High              \
                   AMD         IBM       INTC         AMD         IBM
Date
2025-01-24  122.839996  223.312256  20.830000  125.250000  225.308948
2025-01-27  115.010002  222.646698  20.290001  118.080002  222.815571
2025-01-28  114.169998  224.166565  19.799999  116.150002  224.275838
2025-01-29  117.349998  227.116913  19.750000  118.519997  227.951350
2025-01-30  118.860001  256.560730  20.010000  120.440002  260.067367
2025-01-31  115.949997  254.007751  19.430000  119.570000  255.537553
2025-02-03  114.269997  259.004486  19.379999  115.160004  260.325671
2025-02-04  119.500000  262.709778  19.290001  119.849998  263.494558
2025-02-05  112.010002  261.557434  19.650000  112.089996  263.961432
2025-02-06  110.160004  251.762711  19.379999  112.559998  261.636929
2025-02-07  107.559998  250.669983  19.100000  109.919998  255.229602
2025-02-10  110.480003  249.270004  19.770000  111.400002  251.949997
2025-02-11  111.099998  254.699997  20.969999  113.070000  256.750000
2025-02-12  111.720001  255.809998  22.480000  111.839996  256.399994
2025-02-13  111.809998  259.190002  24.129999  114.599998  259.279999
2025-02-14  113.099998  261.279999  23.600000  114.629997  261.940002
2025-02-18  114.279999  263.070007  27.389999  115.550003  263.959991
2025-02-19  114.690002  264.320007  25.719999  116.110001  264.359985
2025-02-20  114.169998  264.739990  26.090000  116.550003  265.089996
2025-02-21  110.839996  261.480011  24.870001  115.760002  264.829987
2025-02-24  108.110001  261.869995  24.270000  111.599998  263.850006
2025-02-25  103.959999  257.750000  22.990000  108.639999  263.480011
2025-02-26  104.739998  255.839996  23.520000  105.800003  258.329987
2025-02-27   99.510002  253.229996  23.090000  105.760002  257.630005
2025-02-28   99.860001  252.440002  23.730000  101.800003  252.809998
2025-03-03   98.230003  250.190002  22.740000  102.339996  255.990005
2025-03-04  100.750000  253.210007  21.330000  103.180000  255.479996
2025-03-05  101.669998  251.350006  20.809999  101.839996  252.740005
2025-03-06   98.849998  248.690002  20.750000  101.080002  252.100006
2025-03-07  100.309998  261.540009  20.639999  100.650002  261.959991
2025-03-10   96.629997  256.899994  19.930000  101.290001  266.450012
2025-03-11   96.760002  248.949997  19.780001   98.160004  256.700012
2025-03-12  100.790001  249.630005  20.680000  101.720001  253.130005
2025-03-13   98.110001  245.800003  23.700001  100.070000  249.270004
2025-03-14  100.970001  248.350006  24.049999  101.220001  248.949997
2025-03-17  104.589996  252.970001  25.690001  106.150002  254.630005
2025-03-18  103.510002  246.949997  25.920000  104.550003  252.570007
2025-03-19  106.230003  252.289993  24.120001  107.900002  253.660004
2025-03-20  107.139999  243.320007  23.959999  108.260002  246.800003
2025-03-21  106.440002  243.869995  24.260000  107.250000  245.210007
2025-03-24  113.849998  248.449997  24.219999  114.849998  248.820007
2025-03-25  114.809998  249.899994  24.200001  114.949997  250.899994
2025-03-26  110.190002  250.339996  23.420000  115.900002  254.320007
2025-03-27  106.650002  246.210007  23.620001  107.620003  250.300003
2025-03-28  103.220001  244.000000  22.709999  106.510002  247.570007
2025-03-31  102.739998  248.660004  22.709999  102.820000  250.889999
2025-04-01  102.779999  250.339996  22.049999  102.830002  250.619995
2025-04-02  102.959999  249.979996  21.980000  104.190002  252.789993
2025-04-03   93.800003  243.490005  22.430000   99.449997  250.610001
2025-04-04   85.760002  227.479996  19.850000   91.080002  240.160004
2025-04-07   83.639999  225.779999  19.570000   89.000000  232.289993
2025-04-08   78.209999  221.029999  18.129999   88.930000  233.050003
2025-04-09   96.839996  235.309998  21.530001   97.910004  236.300003
2025-04-10   88.699997  229.550003  19.879999   92.949997  232.570007
2025-04-11   93.400002  235.479996  19.740000   94.760002  237.580002
2025-04-14   94.500000  239.059998  20.309999   97.370003  241.770004
2025-04-15   95.290001  240.699997  19.850000   96.849998  241.529999
2025-04-16   88.290001  238.570007  19.230000   90.470001  243.300003
2025-04-17   87.500000  238.809998  18.930000   89.029999  241.779999
2025-04-21   85.559998  236.220001  18.840000   86.139999  240.809998

                              Low                               Open  \
                 INTC         AMD         IBM       INTC         AMD
Date
2025-01-24  21.410000  122.230003  222.318874  20.750000  124.550003
2025-01-27  21.059999  112.800003  218.385081  20.139999  117.800003
2025-01-28  20.340000  112.949997  220.302310  19.740000  115.180000
2025-01-29  20.080000  114.959999  222.249332  19.660000  115.769997
2025-01-30  20.100000  117.089996  245.375255  19.430000  118.529999
2025-01-31  20.330000  115.330002  250.222969  19.379999  119.139999
2025-02-03  19.750000  112.980003  250.173306  18.780001  113.879997
2025-02-04  19.530001  114.790001  256.411740  19.020000  115.449997
2025-02-05  19.770000  106.500000  259.451469  18.910000  107.610001
2025-02-06  19.700001  109.019997  251.057403  19.219999  110.930000
2025-02-07  19.360001  106.790001  250.352109  19.030001  109.129997
2025-02-10  20.080000  108.150002  246.869995  19.240000  108.440002
2025-02-11  21.879999  108.940002  250.580002  19.860001  108.980003
2025-02-12  22.559999  109.059998  252.020004  20.930000  109.519997
2025-02-13  24.830000  110.400002  254.410004  22.790001  112.000000
2025-02-14  25.190001  111.699997  257.910004  22.860001  112.650002
2025-02-18  27.549999  113.449997  259.829987  24.490000  114.050003
2025-02-19  26.330000  113.139999  260.089996  25.459999  114.250000
2025-02-20  26.120001  113.110001  262.149994  24.480000  115.010002
2025-02-21  26.290001  110.430000  261.100006  24.840000  114.849998
2025-02-24  24.799999  107.980003  259.579987  23.620001  111.489998
2025-02-25  24.280001  103.620003  256.769989  22.770000  107.889999
2025-02-26  23.820000  103.989998  254.410004  23.209999  104.949997
2025-02-27  24.400000   99.500000  253.050003  23.070000  105.080002
2025-02-28  24.440001   98.690002  246.539993  22.639999   99.559998
2025-03-03  25.040001   97.089996  248.250000  22.520000  101.519997
2025-03-04  22.629999   95.889999  248.100006  20.760000   96.000000
2025-03-05  21.360001   98.870003  247.009995  20.180000  100.360001
2025-03-06  21.129999   98.269997  246.800003  20.000000   99.050003
2025-03-07  21.200001   96.389999  245.179993  20.110001   98.879997
2025-03-10  20.510000   95.830002  254.750000  19.650000   98.570000
2025-03-11  20.059999   94.730003  245.860001  19.290001   96.790001
2025-03-12  21.170000   98.169998  245.529999  20.209999   99.050003
2025-03-13  24.530001   97.269997  243.039993  23.129999   99.720001
2025-03-14  24.370001   99.580002  241.679993  23.520000   99.639999
2025-03-17  26.150000  102.599998  249.000000  24.370001  102.599998
2025-03-18  26.410000  102.970001  245.119995  25.389999  103.849998
2025-03-19  25.230000  101.959999  246.639999  24.030001  104.419998
2025-03-20  24.309999  105.120003  237.220001  23.730000  105.120003
2025-03-21  24.700001  104.330002  238.500000  23.490000  105.330002
2025-03-24  24.990000  109.400002  245.970001  24.129999  109.730003
2025-03-25  24.750000  112.709999  248.199997  24.110001  113.269997
2025-03-26  24.420000  108.680000  249.529999  23.250000  114.110001
2025-03-27  23.760000  105.550003  245.729996  22.860001  106.110001
2025-03-28  23.580000  102.480003  242.070007  22.559999  105.529999
2025-03-31  22.750000   98.800003  242.490005  21.750000  100.239998
2025-04-01  22.620001  100.930000  243.490005  21.660000  102.160004
2025-04-02  22.379999  100.760002  247.229996  21.700001  101.519997
2025-04-03  23.900000   93.639999  242.529999  20.860001   97.790001
2025-04-04  22.200001   83.669998  226.880005  19.700001   90.099998
2025-04-07  20.670000   77.750000  214.500000  18.559999   80.680000
2025-04-08  20.389999   76.480003  217.279999  17.670000   86.150002
2025-04-09  21.730000   78.870003  215.160004  17.980000   79.220001
2025-04-10  20.820000   85.059998  222.020004  19.160000   91.000000
2025-04-11  19.799999   90.500000  227.509995  18.180000   90.510002
2025-04-14  21.049999   93.449997  236.729996  19.980000   97.110001
2025-04-15  20.469999   94.620003  238.270004  19.809999   94.660004
2025-04-16  19.430000   85.300003  235.889999  18.719999   87.610001
2025-04-17  19.100000   86.519997  237.399994  18.559999   88.839996
2025-04-21  18.990000   83.750000  232.929993  18.250000   86.019997

                                  Volatilidade                       \
                   IBM       INTC          AMD        IBM      INTC
Date
2025-01-24  223.779147  21.360001     3.019997   2.990074  0.660000
2025-01-27  220.719535  20.809999     5.279999   4.430490  0.920000
2025-01-28  222.835437  20.340000     3.200005   3.973528  0.600000
2025-01-29  224.126824  19.870001     3.559998   5.702018  0.420000
2025-01-30  248.345473  19.719999     3.350006  14.692111  0.670000
2025-01-31  254.355426  20.100000     4.239998   5.314584  0.950001
2025-02-03  250.729597  18.969999     2.180000  10.152365  0.969999
2025-02-04  258.279303  19.100000     5.059998   7.082818  0.510000
2025-02-05  263.951488  19.190001     5.589996   4.509962  0.860001
2025-02-06  261.239582  19.510000     3.540001  10.579526  0.480001
2025-02-07  253.590528  19.350000     3.129997   4.877494  0.330000
2025-02-10  250.860001  19.250000     3.250000   5.080002  0.840000
2025-02-11  251.100006  19.870001     4.129997   6.169998  2.019999
2025-02-12  252.720001  21.980000     2.779999   4.379990  1.629999
2025-02-13  255.660004  22.840000     4.199997   4.869995  2.039999
2025-02-14  259.000000  24.360001     2.930000   4.029999  2.330000
2025-02-18  261.929993  24.600000     2.100006   4.130005  3.059999
2025-02-19  262.000000  25.980000     2.970001   4.269989  0.870001
2025-02-20  263.649994  25.559999     3.440002   2.940002  1.640001
2025-02-21  263.850006  25.959999     5.330002   3.729980  1.450001
2025-02-24  261.500000  24.549999     3.619995   4.270020  1.179998
2025-02-25  261.079987  24.209999     5.019997   6.710022  1.510000
2025-02-26  258.100006  23.250000     1.810005   3.919983  0.610001
2025-02-27  255.220001  23.700001     6.260002   4.580002  1.330000
2025-02-28  250.860001  23.020000     3.110001   6.270004  1.800001
2025-03-03  254.740005  25.000000     5.250000   7.740005  2.520000
2025-03-04  248.750000  22.540001     7.290001   7.379990  1.869999
2025-03-05  251.580002  21.330000     2.969994   5.730011  1.180000
2025-03-06  249.750000  20.260000     2.810005   5.300003  1.129999
2025-03-07  245.949997  20.270000     4.260002  16.779999  1.090000
2025-03-10  261.559998  20.240000     5.459999  11.700012  0.860001
2025-03-11  255.990005  19.969999     3.430000  10.840012  0.769999
2025-03-12  250.350006  20.790001     3.550003   7.600006  0.960001
2025-03-13  248.800003  23.500000     2.800003   6.230011  1.400002
2025-03-14  242.750000  23.680000     1.639999   7.270004  0.850000
2025-03-17  249.250000  24.420000     3.550003   5.630005  1.779999
2025-03-18  252.509995  25.549999     1.580002   7.450012  1.020000
2025-03-19  248.330002  24.900000     5.940002   7.020004  1.199999
2025-03-20  244.240005  23.770000     3.139999   9.580002  0.580000
2025-03-21  241.690002  23.600000     2.919998   6.710007  1.210001
2025-03-24  247.309998  24.719999     5.449997   2.850006  0.860001
2025-03-25  248.360001  24.180000     2.239998   2.699997  0.639999
2025-03-26  251.250000  24.250000     7.220001   4.790009  1.170000
2025-03-27  249.710007  23.290001     2.070000   4.570007  0.900000
2025-03-28  246.270004  23.350000     4.029999   5.500000  1.020000
2025-03-31  242.740005  22.379999     4.019997   8.399994  1.000000
2025-04-01  248.029999  22.559999     1.900002   7.129990  0.960001
2025-04-02  248.220001  21.889999     3.430000   5.559998  0.679998
2025-04-03  242.710007  21.400000     5.809998   8.080002  3.039999
2025-04-04  238.000000  21.700001     7.410004  13.279999  2.500000
2025-04-07  219.240005  19.139999    11.250000  17.789993  2.110001
2025-04-08  232.559998  20.059999    12.449997  15.770004  2.719999
2025-04-09  217.119995  18.070000    19.040001  21.139999  3.750000
2025-04-10  231.000000  20.680000     7.889999  10.550003  1.660000
2025-04-11  229.720001  19.250000     4.260002  10.070007  1.619999
2025-04-14  239.770004  20.590000     3.920006   5.040009  1.070000
2025-04-15  239.550003  20.200001     2.229996   3.259995  0.660000
2025-04-16  240.279999  19.340000     5.169998   7.410004  0.710001
2025-04-17  239.679993  18.910000     2.510002   4.380005  0.540001
2025-04-21  238.070007  18.930000     2.389999   7.880005  0.740000

               Volume
                  AMD       IBM       INTC
Date
2025-01-24   31570300   3232900   66300600
2025-01-27   61067900   4898400   83582100
2025-01-28   40554800   4485400   73411400
2025-01-29   40199100   7079800   86506800
2025-01-30   29788400  15381900  108167000
2025-01-31   40533600   7203500  117474900
2025-02-03   34586100   8408500   77523100
2025-02-04   69412100   6077700   54098200
2025-02-05  110385200   6165100   66059200
2025-02-06   50426600   6128300   45553800
2025-02-07   46082500   3370300   58277900
2025-02-10   34905400   3564400   73007300
2025-02-11   35033800   4801600  150960700
2025-02-12   25319700   3075300  162631200
2025-02-13   40911800   4531500  248661300
2025-02-14   32477200   3925300  230254100
2025-02-18   31720300   4262800  284292200
2025-02-19   28807700   3718700  151881700
2025-02-20   27219600   4884800  144939600
2025-02-21   41353700   5667900  111630900
2025-02-24   29072200   4398100   91358100
2025-02-25   39169200   6292200   88886500
2025-02-26   29178200   3460100   67449300
2025-02-27   47263700   3402200   97871900
2025-02-28   45194600   7988800  104133800
2025-03-03   38958000   2977700  141348700
2025-03-04   54156900   5342100  152182200
2025-03-05   27855500   4009800  127219300
2025-03-06   28985000   3254400   96466400
2025-03-07   33254400   6700200   81099600
2025-03-10   38733200   8165500   82760600
2025-03-11   34078300   5630600   80789000
2025-03-12   34241300   3848800  128671100
2025-03-13   28575200   3862400  243261000
2025-03-14   24715300   4045200  116901600
2025-03-17   43689500   3233900  160723600
2025-03-18   27152800   4171900  132488800
2025-03-19   32287500   3853600  135491400
2025-03-20   26871800   7026800   68937600
2025-03-21   30767900   9580100   94110700
2025-03-24   53342000   4753300   69169000
2025-03-25   29077500   3133800   51743300
2025-03-26   39824000   4450100   59496700
2025-03-27   32773700   2889300   57720600
2025-03-28   31069100   3125300   58365300
2025-03-31   30865300   6795000   65832000
2025-04-01   23523200   4412900   64060400
2025-04-02   20794000   4080800   58878800
2025-04-03   50472500   5309600  242972100
2025-04-04   65847000   7407100  175014700
2025-04-07   70515400   7797900  142491200
2025-04-08   69910200   6850000  163982700
2025-04-09   97827400   7302800  224183500
2025-04-10   65210600   5656100  129064900
2025-04-11   57892600   4325900  128425800
2025-04-14   36003000   3321500  101964400
2025-04-15   28116500   3363700   64056900
2025-04-16   62109000   4869900   89469700
2025-04-17   34693400   4626900   85433400
2025-04-21   33774700   4907500   72239200

In [228]:
df_ibm = df.loc['2025-01-24':, colunas]
df_ibm.shape

(60, 6)

In [229]:
df_ibm_viz = df_ibm.stack().reset_index()

C:\Users\hfasa\AppData\Local\Temp\ipykernel_11672\1074650370.py:1: FutureWarning:

The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.

In [230]:
graph = go.Candlestick(
    x = df_ibm_viz.index,
    open = df_ibm_viz.Open,
    close = df_ibm_viz.Close,
    high = df_ibm_viz.High,
    low = df_ibm_viz.Low,
    name = "IBM",
    showlegend = True,
)

In [232]:
layout = Layout(
    title="Gráfico de Candlestick - IBM",
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="rgba(0,0,0,0)",
)

grafico = go.Figure(data=[graph], layout=layout)
grafico.update_xaxes(showgrid=True, gridcolor="lightgrey", gridwidth=1)
grafico.update_yaxes(showgrid=True, gridcolor="lightgrey", gridwidth=1)

grafico